var annotated_dup =
[
    [ "ZEN", null, [
      [ "Macros", "build-info.html#autotoc_md31", null ],
      [ "Example", "build-info.html#autotoc_md32", null ],
      [ "Note", "build-info.html#autotoc_md33", [
        [ "✏️ What is reporting?", "log-reporting.html#autotoc_md27", null ],
        [ "📋 Usage", "log-reporting.html#autotoc_md28", null ],
        [ "Library error", "log-engine-dev.html#autotoc_md26", null ],
        [ "CMake file", "create-modules.html#autotoc_md38", null ],
        [ "Public headers", "create-modules.html#autotoc_md39", null ],
        [ "Integrate in build process", "create-modules.html#autotoc_md40", null ]
      ] ],
      [ "Namespace", "create-modules.html#autotoc_md41", null ],
      [ "How to make callbacks \"a la Zeronetics\"", "callbacks.html#autotoc_md34", null ],
      [ "Examination of choices", "callbacks.html#autotoc_md35", [
        [ "Using <tt>std::optional</tt>", "callbacks.html#autotoc_md36", null ],
        [ "Smart pointers", "callbacks.html#autotoc_md37", null ]
      ] ],
      [ "OpenGL", null, [
        [ "IBindable", "classZEN_1_1OpenGL_1_1IBindable.html", "classZEN_1_1OpenGL_1_1IBindable" ],
        [ "StdBinding", "classZEN_1_1OpenGL_1_1StdBinding.html", "classZEN_1_1OpenGL_1_1StdBinding" ],
        [ "Renderer", "classZEN_1_1OpenGL_1_1Renderer.html", "classZEN_1_1OpenGL_1_1Renderer" ],
        [ "Shader", "classZEN_1_1OpenGL_1_1Shader.html", "classZEN_1_1OpenGL_1_1Shader" ],
        [ "Object", "classZEN_1_1OpenGL_1_1Object.html", null ],
        [ "VAO", "classZEN_1_1OpenGL_1_1VAO.html", "classZEN_1_1OpenGL_1_1VAO" ],
        [ "VBO", "classZEN_1_1OpenGL_1_1VBO.html", "classZEN_1_1OpenGL_1_1VBO" ]
      ] ],
      [ "ICamera3D", "classZEN_1_1ICamera3D.html", "classZEN_1_1ICamera3D" ],
      [ "IInputManager", "classZEN_1_1IInputManager.html", "classZEN_1_1IInputManager" ],
      [ "IRendererRequest", "structZEN_1_1IRendererRequest.html", "structZEN_1_1IRendererRequest" ],
      [ "IRenderGroup3D", "structZEN_1_1IRenderGroup3D.html", "structZEN_1_1IRenderGroup3D" ],
      [ "IRenderManager", "structZEN_1_1IRenderManager.html", "structZEN_1_1IRenderManager" ],
      [ "IRenderable", "classZEN_1_1IRenderable.html", "classZEN_1_1IRenderable" ],
      [ "IRenderable3D", "classZEN_1_1IRenderable3D.html", "classZEN_1_1IRenderable3D" ],
      [ "IRenderer", "classZEN_1_1IRenderer.html", "classZEN_1_1IRenderer" ],
      [ "IShader", "classZEN_1_1IShader.html", "classZEN_1_1IShader" ],
      [ "IShape", "classZEN_1_1IShape.html", "classZEN_1_1IShape" ],
      [ "IShape3D", "classZEN_1_1IShape3D.html", null ],
      [ "ITransforms3D", "classZEN_1_1ITransforms3D.html", "classZEN_1_1ITransforms3D" ],
      [ "IWindow", "classZEN_1_1IWindow.html", "classZEN_1_1IWindow" ],
      [ "BaseInputManager", "classZEN_1_1BaseInputManager.html", null ],
      [ "AABB3D", "classZEN_1_1AABB3D.html", "classZEN_1_1AABB3D" ],
      [ "ColorRGB", "classZEN_1_1ColorRGB.html", null ],
      [ "ColorRGBA", "classZEN_1_1ColorRGBA.html", null ],
      [ "EngineInfo", "structZEN_1_1EngineInfo.html", null ],
      [ "GPUAllocation", "structZEN_1_1GPUAllocation.html", "structZEN_1_1GPUAllocation" ],
      [ "KeyMap", "structZEN_1_1KeyMap.html", null ],
      [ "KeyStateEvent", "structZEN_1_1KeyStateEvent.html", "structZEN_1_1KeyStateEvent" ],
      [ "MousePosition", "structZEN_1_1MousePosition.html", "structZEN_1_1MousePosition" ],
      [ "MouseMovedEvent", "structZEN_1_1MouseMovedEvent.html", "structZEN_1_1MouseMovedEvent" ],
      [ "Path", "classZEN_1_1Path.html", "classZEN_1_1Path" ],
      [ "File", "classZEN_1_1File.html", "classZEN_1_1File" ],
      [ "ScreenResolution", "structZEN_1_1ScreenResolution.html", "structZEN_1_1ScreenResolution" ],
      [ "Settings", "structZEN_1_1Settings.html", "structZEN_1_1Settings" ],
      [ "Shape3D", "classZEN_1_1Shape3D.html", "classZEN_1_1Shape3D" ],
      [ "OS", "structZEN_1_1OS.html", "structZEN_1_1OS" ],
      [ "SystemInfoSheet", "structZEN_1_1SystemInfoSheet.html", "structZEN_1_1SystemInfoSheet" ],
      [ "SystemInfo", "classZEN_1_1SystemInfo.html", null ],
      [ "MVP", "structZEN_1_1MVP.html", "structZEN_1_1MVP" ],
      [ "Version", "structZEN_1_1Version.html", "structZEN_1_1Version" ],
      [ "Vertex3D", "structZEN_1_1Vertex3D.html", "structZEN_1_1Vertex3D" ],
      [ "VertexAttrSize", "classZEN_1_1VertexAttrSize.html", null ],
      [ "Camera3D", "classZEN_1_1Camera3D.html", "classZEN_1_1Camera3D" ],
      [ "Mesh3D", "classZEN_1_1Mesh3D.html", "classZEN_1_1Mesh3D" ],
      [ "Entity", "classZEN_1_1Entity.html", null ],
      [ "Entity3D", "classZEN_1_1Entity3D.html", null ],
      [ "Game", "classZEN_1_1Game.html", "classZEN_1_1Game" ],
      [ "LogFileEntry", "structZEN_1_1LogFileEntry.html", "structZEN_1_1LogFileEntry" ],
      [ "LogBehavior", "structZEN_1_1LogBehavior.html", "structZEN_1_1LogBehavior" ],
      [ "Log", "classZEN_1_1Log.html", null ],
      [ "RendererRequest", "structZEN_1_1RendererRequest.html", null ],
      [ "RenderGroup3D", "structZEN_1_1RenderGroup3D.html", null ],
      [ "RenderManager", "structZEN_1_1RenderManager.html", "structZEN_1_1RenderManager" ],
      [ "Cube", "classZEN_1_1Cube.html", "classZEN_1_1Cube" ],
      [ "HasUniqueId", "classZEN_1_1HasUniqueId.html", "classZEN_1_1HasUniqueId" ],
      [ "Window", "classZEN_1_1Window.html", "classZEN_1_1Window" ]
    ] ]
];