var annotated_dup =
[
    [ "ZEN", "namespaceZEN.html", [
      [ "ControlSystems", null, [
        [ "InputMapping", "classZEN_1_1ControlSystems_1_1InputMapping.html", "classZEN_1_1ControlSystems_1_1InputMapping" ],
        [ "SignalHandler", "classZEN_1_1ControlSystems_1_1SignalHandler.html", "classZEN_1_1ControlSystems_1_1SignalHandler" ],
        [ "ControlManager", "classZEN_1_1ControlSystems_1_1ControlManager.html", "classZEN_1_1ControlSystems_1_1ControlManager" ]
      ] ],
      [ "Gizmos", null, [
        [ "Grid3D", "classZEN_1_1Gizmos_1_1Grid3D.html", "classZEN_1_1Gizmos_1_1Grid3D" ]
      ] ],
      [ "OpenGL", null, [
        [ "IBindable", "classZEN_1_1OpenGL_1_1IBindable.html", "classZEN_1_1OpenGL_1_1IBindable" ],
        [ "StdBinding", "classZEN_1_1OpenGL_1_1StdBinding.html", "classZEN_1_1OpenGL_1_1StdBinding" ],
        [ "Renderer", "classZEN_1_1OpenGL_1_1Renderer.html", "classZEN_1_1OpenGL_1_1Renderer" ],
        [ "Shader", "classZEN_1_1OpenGL_1_1Shader.html", "classZEN_1_1OpenGL_1_1Shader" ],
        [ "Object", "classZEN_1_1OpenGL_1_1Object.html", null ],
        [ "VAO", "classZEN_1_1OpenGL_1_1VAO.html", "classZEN_1_1OpenGL_1_1VAO" ],
        [ "VBO", "classZEN_1_1OpenGL_1_1VBO.html", "classZEN_1_1OpenGL_1_1VBO" ]
      ] ],
      [ "Tests", null, [
        [ "ControlSystemsTest", "classZEN_1_1Tests_1_1ControlSystemsTest.html", "classZEN_1_1Tests_1_1ControlSystemsTest" ],
        [ "GLSLShaderBuilderTest", "classZEN_1_1Tests_1_1GLSLShaderBuilderTest.html", "classZEN_1_1Tests_1_1GLSLShaderBuilderTest" ]
      ] ],
      [ "ICamera3D", "classZEN_1_1ICamera3D.html", "classZEN_1_1ICamera3D" ],
      [ "IInputManager", "classZEN_1_1IInputManager.html", "classZEN_1_1IInputManager" ],
      [ "IRenderGroup3D", "structZEN_1_1IRenderGroup3D.html", "structZEN_1_1IRenderGroup3D" ],
      [ "IRenderLayer", "classZEN_1_1IRenderLayer.html", "classZEN_1_1IRenderLayer" ],
      [ "IRendererRequest", "structZEN_1_1IRendererRequest.html", "structZEN_1_1IRendererRequest" ],
      [ "IRenderManager", "structZEN_1_1IRenderManager.html", "structZEN_1_1IRenderManager" ],
      [ "IRenderable", "classZEN_1_1IRenderable.html", "classZEN_1_1IRenderable" ],
      [ "IRenderable3D", "classZEN_1_1IRenderable3D.html", "classZEN_1_1IRenderable3D" ],
      [ "IRenderer", "classZEN_1_1IRenderer.html", "classZEN_1_1IRenderer" ],
      [ "IShaderBuilder", "classZEN_1_1IShaderBuilder.html", "classZEN_1_1IShaderBuilder" ],
      [ "IShader", "classZEN_1_1IShader.html", "classZEN_1_1IShader" ],
      [ "IShape", "classZEN_1_1IShape.html", "classZEN_1_1IShape" ],
      [ "IShape3D", "classZEN_1_1IShape3D.html", null ],
      [ "ITransforms3D", "classZEN_1_1ITransforms3D.html", "classZEN_1_1ITransforms3D" ],
      [ "IWindow", "classZEN_1_1IWindow.html", "classZEN_1_1IWindow" ],
      [ "BaseInputManager", "classZEN_1_1BaseInputManager.html", null ],
      [ "AABB3D", "classZEN_1_1AABB3D.html", "classZEN_1_1AABB3D" ],
      [ "ColorRGB", "classZEN_1_1ColorRGB.html", null ],
      [ "ColorRGBA", "classZEN_1_1ColorRGBA.html", null ],
      [ "EngineInfo", "structZEN_1_1EngineInfo.html", null ],
      [ "GPUAllocation", "structZEN_1_1GPUAllocation.html", "structZEN_1_1GPUAllocation" ],
      [ "KeyMap", "structZEN_1_1KeyMap.html", null ],
      [ "KeyStateEvent", "structZEN_1_1KeyStateEvent.html", "structZEN_1_1KeyStateEvent" ],
      [ "MouseButtonStateEvent", "structZEN_1_1MouseButtonStateEvent.html", "structZEN_1_1MouseButtonStateEvent" ],
      [ "KeyDownEvent", "structZEN_1_1KeyDownEvent.html", "structZEN_1_1KeyDownEvent" ],
      [ "MouseButtonDownEvent", "structZEN_1_1MouseButtonDownEvent.html", "structZEN_1_1MouseButtonDownEvent" ],
      [ "MousePosition", "structZEN_1_1MousePosition.html", "structZEN_1_1MousePosition" ],
      [ "MouseMovedEvent", "structZEN_1_1MouseMovedEvent.html", "structZEN_1_1MouseMovedEvent" ],
      [ "Path", "classZEN_1_1Path.html", "classZEN_1_1Path" ],
      [ "File", "classZEN_1_1File.html", "classZEN_1_1File" ],
      [ "ObserverMeta", "structZEN_1_1ObserverMeta.html", null ],
      [ "Observation", "structZEN_1_1Observation.html", "structZEN_1_1Observation" ],
      [ "Observer", "classZEN_1_1Observer.html", "classZEN_1_1Observer" ],
      [ "BeingObserved", "classZEN_1_1BeingObserved.html", "classZEN_1_1BeingObserved" ],
      [ "ResultError", "structZEN_1_1ResultError.html", "structZEN_1_1ResultError" ],
      [ "Result", "classZEN_1_1Result.html", "classZEN_1_1Result" ],
      [ "ScreenResolution", "structZEN_1_1ScreenResolution.html", "structZEN_1_1ScreenResolution" ],
      [ "Settings", "structZEN_1_1Settings.html", "structZEN_1_1Settings" ],
      [ "ShaderBlueprint", "structZEN_1_1ShaderBlueprint.html", "structZEN_1_1ShaderBlueprint" ],
      [ "Shape3D", "classZEN_1_1Shape3D.html", "classZEN_1_1Shape3D" ],
      [ "OS", "structZEN_1_1OS.html", "structZEN_1_1OS" ],
      [ "SystemInfoSheet", "structZEN_1_1SystemInfoSheet.html", "structZEN_1_1SystemInfoSheet" ],
      [ "SystemInfo", "classZEN_1_1SystemInfo.html", null ],
      [ "MVP", "structZEN_1_1MVP.html", "structZEN_1_1MVP" ],
      [ "TimeMeasurement", "structZEN_1_1TimeMeasurement.html", "structZEN_1_1TimeMeasurement" ],
      [ "Timer", "classZEN_1_1Timer.html", "classZEN_1_1Timer" ],
      [ "Version", "structZEN_1_1Version.html", "structZEN_1_1Version" ],
      [ "Vertex3D", "structZEN_1_1Vertex3D.html", "structZEN_1_1Vertex3D" ],
      [ "VertexAttrName", "classZEN_1_1VertexAttrName.html", null ],
      [ "VertexAttrSize", "classZEN_1_1VertexAttrSize.html", null ],
      [ "Camera3D", "classZEN_1_1Camera3D.html", "classZEN_1_1Camera3D" ],
      [ "Mesh3D", "classZEN_1_1Mesh3D.html", "classZEN_1_1Mesh3D" ],
      [ "Entity", "classZEN_1_1Entity.html", null ],
      [ "Entity3D", "classZEN_1_1Entity3D.html", null ],
      [ "Game", "classZEN_1_1Game.html", "classZEN_1_1Game" ],
      [ "Strings", "classZEN_1_1Strings.html", null ],
      [ "LogFileEntry", "structZEN_1_1LogFileEntry.html", "structZEN_1_1LogFileEntry" ],
      [ "LogBehavior", "structZEN_1_1LogBehavior.html", "structZEN_1_1LogBehavior" ],
      [ "Log", "classZEN_1_1Log.html", null ],
      [ "Process", "classZEN_1_1Process.html", "classZEN_1_1Process" ],
      [ "RendererRequest", "structZEN_1_1RendererRequest.html", null ],
      [ "RenderGroup3D", "structZEN_1_1RenderGroup3D.html", null ],
      [ "RenderLayer", "classZEN_1_1RenderLayer.html", "classZEN_1_1RenderLayer" ],
      [ "RenderManager", "structZEN_1_1RenderManager.html", "structZEN_1_1RenderManager" ],
      [ "Cube", "classZEN_1_1Cube.html", "classZEN_1_1Cube" ],
      [ "HasUniqueId", "classZEN_1_1HasUniqueId.html", "classZEN_1_1HasUniqueId" ],
      [ "Processor", "classZEN_1_1Processor.html", "classZEN_1_1Processor" ],
      [ "Window", "classZEN_1_1Window.html", "classZEN_1_1Window" ],
      [ "GLSLShaderBuilder", "classZEN_1_1GLSLShaderBuilder.html", "classZEN_1_1GLSLShaderBuilder" ]
    ] ]
];