var NAVTREEINDEX0 =
{
"annotated.html":[2,0],
"arch.html":[1],
"arch.html#autotoc_md0":[0],
"arch.html#autotoc_md1":[1],
"arch.html#autotoc_md2":[1,0],
"arch.html#autotoc_md3":[1,1],
"arch.html#autotoc_md4":[1,2],
"classENGINE__NAMESPACE_1_1EngineInfo.html":[2,0,2,2],
"classENGINE__NAMESPACE_1_1GlfwWindow.html":[2,0,2,3],
"classENGINE__NAMESPACE_1_1IRenderer.html":[2,0,2,1],
"classENGINE__NAMESPACE_1_1IWindow.html":[2,0,2,0],
"classes.html":[2,1],
"hierarchy.html":[2,2],
"index.html":[],
"index.html":[0],
"pages.html":[]
};
