
# Create the autoload directory
file(MAKE_DIRECTORY ${ZEN_AUTOLOAD_DIR})

# Set filename
set(ZEN_AUTOLOAD_CPP_FILE ${ZEN_AUTOLOAD_DIR}/autoload.cpp)

# Create the content of autoload.cpp
file(WRITE ${ZEN_AUTOLOAD_CPP_FILE} "/**\n"
    " * Zeronetics Autoload File\n"
    " *\n"
    " * This file was generated by the CMake process.\n"
    " *\n"
    " * PLEASE NOTE:\n"
    " * This file is automatically generated, and might be overwritten again.\n"
    " * Changes made to this file should be expected to be lost.\n"
    " */\n"
    "\n"
    "namespace ZEN {\n"
    "\tclass EntityRegistry {\n"
    "\n"
    "\t};\n"
    "}\n")
